version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo "Installing dependencies..."
      - npm ci --include=dev
  build:
    commands:
      - echo "Compiling TypeScript..."
      - npm run build
      - zip -r app.zip dist package.json package-lock.json
artifacts:
  files:
    - app.zip
  base-directory: .
