version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo "Installing dependencies..."
      - npm ci --include=dev
  build:
    commands:
      - echo "Compiling TypeScript..."
      - npm run build
artifacts:
  files:
    - '**/*'
  base-directory: .
