version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo "Installing dependencies..."
      - npm ci --include=dev
  build:
    commands:
      - echo "Compiling TypeScript..."
      - npm run build
artifacts:
  files:
    - package-lock.json
    - package.json
    - "dist/**/*"
    # - '.platform/**/*' # AWS Elastic Beanstalk configuration files
    # - '.ebextensions/**/*' # AWS Elastic Beanstalk configuration files
  base-directory: .
